### ISSUE TITLE
[MACAÉ] Desenvolvedor [EmapX]

### ISSUE THREAD

**Issue by cinthiabpessanha** [MacaeTech/vagas#1]
## Empresa
  EmapX (https://www.emapx.com/) 
   ## Cargo
   Desenvolvedor      
   ## Descrição da vaga
   O profissional atuará em atividades de desenvolvimento  
   ## Requisitos obrigatórios
   ASP. Net MVC, SQL Server, HTML 5     
   ## Diferenciais
  Java, JavaScript
   ## Tempo de experiência      
   Não é necessário        
   ## Modalidade
   Estágio / Formado / Venturing      
   ## Salário
   A negociar    
   ## Carga horária
   Não informado 
   ## Benefícios
   Não informado
   ## Como se candidatar
   Enviar email para contato@emapx.com

**Comment by jhongalante** [comment]
Ainda tá disponível essa vaga?
